# Generated by Django 2.2.7 on 2023-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0006_auto_20230526_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='arena', max_length=50),
        ),
    ]
