# Generated by Django 4.1.7 on 2023-05-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='game',
        ),
    ]
