# Generated by Django 4.1.7 on 2023-05-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_remove_booking_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='arena.game'),
        ),
    ]
