# Generated by Django 2.2.7 on 2023-05-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0007_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='Arena', max_length=50),
        ),
    ]
