# Generated by Django 2.2.7 on 2023-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0009_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateField(),
        ),
    ]
